---
title: "MATH153, Lab 1"
author: "Senan Hogan-H."
date: "8 February 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE, fig.align="center")
gc()
ls()
options(digits=4)
require(tidyverse)
set.seed(47)
```

## Question 1.

a.
Need $\frac{\alpha}{\alpha+\beta} = .1$, so $9\alpha = \beta$.

$\Rightarrow$ want $pbeta(.2, \alpha, \beta) = .9$.
```{r}
x <- 0.2
# a/(a+b) = 0.1, so b = 9a
vector <- seq(0, 10000, 0.001)
i <- 1
a <- vector[i]
b <- 9*a
while (abs(pbeta(x,a,b) - 0.9) > 0.001){
  i <- i + 1
  a <- vector[i]
  b <- 9*a
}
rm(vector, i)
a
b
pbeta(x,a,b) # roughly = 0.9
```
b. 
Need $\frac{\alpha}{\alpha+\beta} = mean$, so $\frac{\alpha (1- mean)}{mean} = \beta$.

$\Rightarrow$ want $pbeta(x, \alpha, \beta) = prob$.
```{r}
ab_finder <- function(mean, x, prob){
  vector <- seq(0, 100, 0.001)
  i <- 1
  a <- vector[i]
  # a/(a+b) = mean
  b <- a*(1 - mean)*(1/mean)
  while (abs(pbeta(x,a,b) - prob) > 0.001){
    i <- i + 1
    a <- vector[i]
    b <- a*(1 - mean)*(1/mean)
  }
  rm(vector, i)
  return(c(a,b))
}
ab_finder(0.1, 0.2, 0.9) # test the function.
```

## Question 2.

a.
```{r, fig.height = 3, fig.width = 6.5, fig.align='center'}
# Prior for p is beta (1.59, 14.31)\
alpha = 1.59
beta = 14.31
nP = 100 # Number of p's
nX = c(2, 4, 8, 15, 20, 35, 70, 100, 250) #Vector of sample sizes for the binomial experiments
sampleP = rbeta(nP, alpha, beta)
resultsMSE = matrix(nrow = (nP*length(nX)), ncol = 4)
colnames(resultsMSE) = c("mse_bayes", "mse_mle", "p", "n")
resultsMAE = matrix(nrow = (nP*length(nX)), ncol = 5)
colnames(resultsMAE) = c("mae_bayes_median", "mae_bayes_mean", "mae_mle", "p", "n")

j=1
for(i in 1:nP){
  for(n in nX){
    x = rbinom(1, n, sampleP[i])
    mse_mle = (sampleP[i]-x/n)^2
    mse_bayes = (sampleP[i]-(alpha+x)/(alpha+n+beta))^2
    mae_mle = abs(sampleP[i]-x/n)
    mae_bayes_mean = abs(sampleP[i]-(alpha+x)/(alpha+n+beta))
    mae_bayes_med = abs(sampleP[i]-(alpha+x-1/3)/(alpha+n+beta-2/3))
    resultsMSE[j,] = c(mae_bayes_mean, mae_mle, sampleP[i], n)
    resultsMAE[j,] = c(mae_bayes_med, mae_bayes_mean, mae_mle, sampleP[i], n)
    j=j+1
  }
}

bayesMeans_bySampleSize = c()
freqMeans_bySampleSize = c()
for(i in 1:length(nX)){
  bayesMeans_bySampleSize[i] = mean(resultsMSE[which(resultsMSE[,4]==nX[i]),1])
  freqMeans_bySampleSize[i] = mean(resultsMSE[which(resultsMSE[,4]==nX[i]),2])
}

sortedP = sort(sampleP)
bayesMeans_byP = c()
freqMeans_byP = c()
for(i in 1:length(sortedP)){
  bayesMeans_byP[i] = mean(resultsMSE[which(resultsMSE[,3]==sortedP[i]),1])
  freqMeans_byP[i] = mean(resultsMSE[which(resultsMSE[,3]==sortedP[i]),2])
}

plot(bayesMeans_bySampleSize~nX, main = "Bayes MSE with Growing Sample Size", xlab = "Sample Size", ylab = "MSE", col = 'red', type = 'l')
lines(freqMeans_bySampleSize~nX, col = 'green')
legend("topright", legend=c("Posterior Mean", "MLE"), col=c("red", "green"), lty=1:2, cex=0.8)

plot(bayesMeans_byP~sortedP, main = "MSE with Growing P Value", xlab = "P value", ylab = "MSE", col = 'red', type = 'l')
lines(freqMeans_byP~sortedP, col = 'green')
legend("topright", legend=c("Posterior Mean", "MLE"), col=c("red", "green"), lty=1:2, cex=0.8)
```

b.
```{r, fig.height = 3, fig.width = 6.5, fig.align='center'}
bayesMeansMAE_bySampleSize = c()
bayesMedsMAE_bySampleSize = c()
freqMeansMAE_bySampleSize = c()
for(i in 1:length(nX)){
  bayesMedsMAE_bySampleSize[i] = mean(resultsMAE[which(resultsMAE[,5]==nX[i]),1])
  bayesMeansMAE_bySampleSize[i] = mean(resultsMAE[which(resultsMAE[,5]==nX[i]),2])
  freqMeansMAE_bySampleSize[i] = mean(resultsMAE[which(resultsMAE[,5]==nX[i]),3])
}

bayesMedsMAE_byP = c()
bayesMeansMAE_byP = c()
freqMeansMAE_byP = c()
for(i in 1:length(sortedP)){
  bayesMedsMAE_byP[i] = mean(resultsMAE[which(resultsMAE[,4]==sortedP[i]),1])
  bayesMeansMAE_byP[i] = mean(resultsMAE[which(resultsMAE[,4]==sortedP[i]),2])
  freqMeansMAE_byP[i] = mean(resultsMAE[which(resultsMAE[,4]==sortedP[i]),3])
}

plot(bayesMeansMAE_bySampleSize~nX, main = "Bayes MAE with Growing Sample Size", xlab = "Sample Size", ylab = "MAE", col = 'red', type = 'l')
lines(freqMeansMAE_bySampleSize~nX, col = 'green')
lines(bayesMedsMAE_bySampleSize~nX, col = 'blue')
legend("topright", legend=c("Posterior Mean", "MLE", "Posterior Median"), col=c("red", "green", "blue"), lty=1:2, cex=0.8)

plot(bayesMeansMAE_byP~sortedP, main = "MAE with Growing P Value", xlab = "P value", ylab = "MAE", col = 'red', type = 'l')
lines(freqMeansMAE_byP~sortedP, col = 'green')
lines(bayesMedsMAE_byP~sortedP, col = 'blue')
legend("bottomright", legend=c("Posterior Mean", "MLE", "Posterior Median"), col=c("red", "green", "blue"), lty=1:2, cex=0.8)
rm(list = ls())
```

## Question 3.

a.
Start with an informative prior, as outlined in question 1 for $p=0.1$.
```{r, fig.height = 3, fig.width = 6.5, fig.align='center'}
p <- 0.1
alpha <- ab_finder(0.1, 0.2, 0.9)[1] 
beta <- ab_finder(0.1, 0.2, 0.9)[2]

x <- rbeta(10, alpha, beta)
x_1<- rbeta(10, alpha + mean(x), beta + length(x) - mean(x))
x <- rbeta(100, alpha, beta)
x_2<- rbeta(100, alpha + mean(x), beta + length(x) - mean(x))
x <- rbeta(1000, alpha, beta)
x_3<- rbeta(1000, alpha + mean(x), beta + length(x) - mean(x))

plot.multi.dens <- function(s)
{
    junk.x = NULL
    junk.y = NULL
    for(i in 1:length(s)) {
        junk.x = c(junk.x, density(s[[i]])$x)
        junk.y = c(junk.y, density(s[[i]])$y)
    }
    xr <- range(junk.x)
    yr <- range(junk.y)
    plot(density(s[[1]]), xlim = xr, ylim = yr, main = "")
    for(i in 1:length(s)) {
        lines(density(s[[i]]), xlim = xr, ylim = yr, col = i)
    }
}

# the input of the following function MUST be a numeric list
plot.multi.dens( list(x_1, x_2))

```

